image: golang:1.11.2


before_script:
  - mkdir -p $GOPATH/src/github.com/louistsaitszho/graphql
  - cp -r $CI_PROJECT_DIR $GOPATH/src/github.com/louistsaitszho/graphql

stages:
  - test

unit_tests:
  stage: test
  script:
    - go test

# race_detector:
#   stage: test
#   script:
#     - make race

# memory_sanitizer:
#   stage: test
#   script:
#     - make msan