openapi: 3.0.2
info:
  title: Loft API
  version: 1.0.0
  contact:
    name: Louis Tsai
    url: https://louistsaitszho.github.io
    email: tsaitszho@gmail.com
tags:
  - name: loft
    description: General loft info
  - name: tasks
    description: Tasks of a loft
  - name: notes
    description: Notes of a loft
  - name: roommates
    description: Peoples of a loft
  - name: status
    description: Status of the API
servers: 
  - url: TBC (Staging)
    description: Staging server, data cloned from production (PID removed) once a week
  - url: TBC (Production)
    description: Production server
paths:
  /echo:
    get:
      tags: 
        - status
      responses:
        200:
          description: Return received server time (like an actual echo, get it?)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: dateTime
              example:
                message: '2018-01-01T00:00:00-00:00'
  /loft:
    post:
      summary: Create a new loft
      tags:
        - loft
      requestBody:
        description: Data that's needed to create a new loft
        content:
          application/json:
            schema:
              type: object
              properties: 
                user_name:
                  type: string
                loft_name:
                  type: string
      responses:
        200:
          description: Create a new loft successful, and return loft and user info
          content:
            application/json:
                schema:
                  type: object
                  properties:
                    loft:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                    user:
                      type: object
  /loft/{loftId}:
    get:
    put:
    patch:
  /loft/{loftId}/requests:
    post:
    get:
  /loft/{loftId}/notes:
    get:
    post:
  /loft/{loftId}/notes/{noteId}:
    get:
    put:
    patch:
  /loft/{loftId}/tasks:
    get:
    post:
  /loft/{loftId}/tasks/{taskId}:
    get:
    put:
    patch:
  /loft/{loftId}/members:
    get:
  /loft/{loftId}/members/{memberId}:
    get:
externalDocs:
  description: API GitHub Repository
  url: https://github.com/louistsaitszho/loft-API